name: publish

on:
  push:
    branches:
      - master

jobs:
  plot_publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip -r requirements.txt
        pip install -U https://github.com/benchopt/benchOpt/archive/master.zip
    - name: Plot and publish
      run: |
        make publish
